---
version: 2.0
jobs:
  test-job:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: echo test
    working_directory: /usr/src/artman/

workflows:
  version: 2
  tests:
    jobs:
      - test-job:
          filters: &all_commits
            tags:
              only: /.*/
