---
version: 2.0
jobs:
  unit-python3.6:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: apt-get install openssl
      - run: openssl --version
      - run:
          name: Install nox and codecov.
          command: pip install --upgrade nox-automation codecov
      - run:
          name: Run unit tests.
          command: nox -e "unit_tests(python_version='3.6')"
    working_directory: /usr/src/artman/

workflows:
  version: 2
  tests:
    jobs:
      - unit-python3.6:
          filters: &all_commits
            tags:
              only: /.*/
